config/routes.rb
Rails.application.routes.draw do

  # resources :msgs
  # resources :chats
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # resources :postcomments

  resources :posts do
    resources :postcomments
    resources :likes
  end

  # resources :posts do
  #   resources :likes
  # end

  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root to: "posts#index"

  resources :users, except: [:show] do
    member do
      get :following, :followers
      get :blocking, :blocked_by
    end
    collection do
      get :search
    end
  end

  get '/users/:user_name', to: 'users#show'

  resources :conversations do
    resources :messages
  end

  resources :chats do
    resources :msgs
  end

  get "/profile" => "users#profile"
  resources :relationships,       only: [:create, :destroy]
  resources :blocks,       only: [:create, :destroy]

  # API
  namespace :api do
    namespace :v1 do

     resources :posts
     resources :users
     resources :postcomments
     resources :likes
     resources :relationships do
       collection do
         post :follow
         post :unfollow
       end
     end
     resources :blocks do
       collection do
         post :block
         post :unblock
       end
     end

    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/views/conversations/index.html.erb
<h1>All Conversations</h1>

<div align = "left">
  <% @conversations.each do |conversation| %>
    <div>
      <%= link_to conversation.subject, conversation_path(conversation) %>
    </div>
  <% end %>

  <%= link_to "New Conversation", new_conversation_path %>
</div>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<div align = "left">
  <%= form_tag conversations_path, method: :post do %>
    <div>
      <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :name), :class=>'gapping' %>
    </div>
    <div>
      <%= text_field_tag :subject, nil, placeholder: "Subject", :class=>'gapping' %>
    </div>
    <div>
      <%= text_area_tag :body, nil, placeholder: "Message", :class=>'gapping' %>
    </div>
    <%= submit_tag %>
  <% end %>
</div>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>
<div align = "left">
  <% @conversation.receipts_for(current_user).each do |receipt|%>
    <div>
      <div>
        <h7><%= receipt.message.sender.name %></h7>
      </div>
    <p><%= receipt.message.body %></p>
    </div>
  <% end %>

  <%= form_tag conversation_messages_path(@conversation), method: :post do %>
    <div>
      <%= text_area_tag :body %>
    </div>

    <%= submit_tag %>
  <% end %>

</div>