config/routes.rb
Rails.application.routes.draw do

  # resources :msgs
  # resources :chats
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # resources :postcomments

  resources :posts do
    resources :postcomments
    resources :likes
  end

  # resources :posts do
  #   resources :likes
  # end

  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root to: "posts#index"

  resources :users, except: [:show] do
    member do
      get :following, :followers
      get :blocking, :blocked_by
    end
    collection do
      get :search
    end
  end

  get '/users/:user_name', to: 'users#show'

  resources :conversations do
    resources :messages
  end

  resources :chats do
    resources :msgs
  end

  get "/profile" => "users#profile"
  resources :relationships,       only: [:create, :destroy]
  resources :blocks,       only: [:create, :destroy]

  # API
  namespace :api do
    namespace :v1 do

     resources :posts
     resources :users
     resources :postcomments
     resources :likes
     resources :relationships do
       collection do
         post :follow
         post :unfollow
       end
     end
     resources :blocks do
       collection do
         post :block
         post :unblock
       end
     end

    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  acts_as_messageable

  # for change in url of user's profile
  # extend FriendlyId
  # friendly_id :user_name, use: :slugged

  # devise authentication
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #doorkeeper
  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end

  # Relationships
  has_many :posts, dependent: :destroy
  has_many :postcomments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image

  # validation to user model
  validates :name, presence: true
  validates :user_name, presence: true, uniqueness: true, length: {minimum: 5, maximum: 20}
  validates :email, presence: true, uniqueness: true
  validates :phone_no, presence: true, uniqueness: true, length: {maximum: 10}
  validates :bio, length: {maximum: 150}

  #doorkeeper
  has_many :access_grants,
           class_name: 'Doorkeeper::AccessGrant',
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
           class_name: 'Doorkeeper::AccessToken',
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  # Follow feature
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower


  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # Block feature
  has_many :active_blocks,  class_name:  "Block",
                                  foreign_key: "blocked_by_id",
                                  dependent:   :destroy
  has_many :blocking, through: :active_blocks,  source: :blocked

  has_many :passive_blocks, class_name:  "Block",
                                  foreign_key: "blocked_id",
                                  dependent:   :destroy
  has_many :blocked_by, through: :passive_blocks, source: :blocked_by

  # Blocks a user.
  def block(other_user)
    active_blocks.create(blocked_id: other_user.id)
  end

  # Unblocks a user.
  def unblock(other_user)
    active_blocks.find_by(blocked_id: other_user.id).destroy
  end

  # Returns true if the current user is blocking the other user.
  def blocking?(other_user)
    blocking.include?(other_user)
  end

  #csv download
  def self.to_csv
    attributes = %w{id email name user_name bio phone_no}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << user.attributes.values_at(*attributes)
      end
    end
  end

  # for Search
  def self.search(user_name)
    if user_name
      user_name.downcase!
      where('LOWER(user_name) LIKE ?', "%#{user_name}%")
    else
      all
    end
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController

  before_action :set_user, only: %i[ show edit update destroy ]
  # skip_before_action :verify_authenticity_token
  # before_action :find_user, only: :show

  def index
    @users = User.all
    render json: @users
  end

  def show
    render json: @user
  end

  def create
   p "------#{user_params}"
   @user = User.new(user_params)
   if @user.save
    render json: @user
   else
    render json: @user.errors
   end
  end

  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors
    end
  end

  def destroy
    @user.destroy
  end

  private
    # def set_user
    #   @user = User.find(params[:id])
    # end
    def set_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.to_s }, status: :not_found
    end

    def user_params
      params.require(:user).permit(:name, :user_name, :email, :phone_no, :bio, :image, :password, :password_confirmation)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers, :blocking, :blocked_by]

  def following
    title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    # render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    # render 'show_follow'
  end

  def blocking
    title = "Blocking"
    @user  = User.find(params[:id])
    @users = @user.blocking.paginate(page: params[:page])
    # render 'show_follow'
  end

  def blocked_by
    @title = "Blocked_by"
    @user  = User.find(params[:id])
    @users = @user.blocked_by.paginate(page: params[:page])
    # render 'show_follow'
  end

  def index
    if params[:search].present?
      @users = User.search(params[:search])
    else
      @users = User.where.not(id: current_user.id)
    end

    # for csv
    @datas = User.where(id: current_user.id)
    respond_to do |format|
      format.html
      format.csv { send_data @datas.to_csv }
    end
  end

  def edit
  end

  def show
    # @user = User.find_by_id(params[:id])
    # @user = User.friendly.find(params[:id])
    @user = User.find_by_user_name(params[:user_name])
    if @user.nil?
      @user = User.find_by_id(params[:user_name])
    end

  end

  def profile
    # @user = User.find_by_id(params[:current_user.id])
    # @user = User.find(current_user.id)
    # @user = User.friendly.find(current_user.id)
    redirect_to current_user
  end

  def search
    @users = User.search(params[:search])
  end

  private
    # Confirms a logged-in user.
    def logged_in_user
      # unless logged_in?
      #   store_location
      #   flash[:danger] = "Please log in."
      #   redirect_to login_url
      # end
    end

end

app/views/users/_block.html.erb
<%= form_for(current_user.active_blocks.build) do |f| %>
  <div><%= hidden_field_tag :blocked_id, @user.id %></div>
  <%= f.submit "Block", class: "btn btn-danger " %>
<% end %>

app/views/users/_block_form.html.erb
<div class="block">
  <% if current_user.blocking?(@user) %>
    <%= render 'unblock' %>
  <% else %>
    <%= render 'block' %>
  <% end %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary " %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
<% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
<% else %>
  <%= render 'follow' %>
<% end %>
</div>

app/views/users/_unblock.html.erb
<%= form_for(current_user.active_blocks.find_by(blocked_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unblock", class: "btn btn-success" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-danger " %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="main">
  <div class="subsection">
    <h1>Users on Instagram</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Username</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
              <td align = "left"><%= link_to user.name, user, class: "hober" %></td>
              <td align = "left"><%= user.user_name %></td>
              <td><%=  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
  </div>

  <div class="subsection3">
    <%= link_to "Current User Details", users_path(format: "csv"), :class=>"btn btn-outline-info btn-lg" %>
  </div>
</div>

app/views/users/profile.html.erb
  <p id="notice"><%= notice %></p>

  <div class="card" style="width: 18rem;">
    <% if @current_user.image.representable? %>
      <%= image_tag @current_user.image.representation(resize_to_limit: [200, 200]) %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><p>
        <strong>User: </strong>
        <%= @current_user.name %>
      </p></h5>
      <h5 class="card-title"><p>
        <strong>Username: </strong>
        <%= @current_user.user_name %>
      </p></h5>
      <h5 class="card-title"><p>
        <strong>Bio: </strong>
        <%= @current_user.bio %>
      </p></h5>
      <p class="card-text"><strong>Followers: </strong>
      <%= @current_user.followers.count %></p>
      <p class="card-text"><strong>Following: </strong>
      <%= @current_user.following.count %></p>
      <%= link_to "Edit profile", edit_user_registration_path %>
    </div>
  </div>

<ul>
  <% current_user.posts.each do |post| %>
    <li>
      <% post.images.each do |file| %>
        <% if file.representable? %>
          <%= image_tag file.representation(resize_to_limit: [400, 400]) %>
        <% end %>
      <% end %>
    </li>
    <p>
      <strong>Like: </strong>
      <%= post.likes.count %>
    </p>
    <p>
      
      <%= post.caption %>
    </p>
    <h5>Comments</h5>
    <%= render post.postcomments %>

    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

</ul>

app/views/users/profile1.html.erb
<% if @current_user.image.representable? %>
  <%= image_tag @current_user.image.representation(resize_to_limit: [300, 300]) %>
<% end %>


<p>
  <strong>User: </strong>
  <%= @current_user.name %>
</p>
<p>
  <strong>Username: </strong>
  <%= @current_user.user_name %>
</p>
<p>
  <strong>Bio: </strong>
  <%= @current_user.bio %>
</p>
<p>
  <strong>Followers: </strong>
  <%= @current_user.followers.count %>
</p>
<p>
  <strong>Following: </strong>
  <%= @current_user.following.count %>
</p>

<ul>
  <% current_user.posts.each do |post| %>
    <li>
      <% post.images.each do |file| %>
        <% if file.representable? %>
          <%= image_tag file.representation(resize_to_limit: [400, 400]) %>
        <% end %>
      <% end %>
    </li>
    <p>
      <strong>Like: </strong>
      <%= post.likes.count %>
    </p>
    <p>
      <strong>Caption:</strong>
      <%= post.caption %>
    </p>
    <h7>Comments</h7>
    <%= render post.postcomments %>

    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

</ul>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if @user.present? %>

  <div align = "left">
    <div class="first">
      <div class="second">
        <% if @user.image.representable? %>
          <%= image_tag @user.image.representation(resize_to_limit: [300, 300]), :class=> "img-circular" %>
        <% end %>
      </div>
      <div class="second">
        <% if @user == current_user %>
          <%= link_to "Edit profile", edit_user_registration_path, :class=>"btn btn-outline-dark" %>
        <% end %>
      </div>
    </div>

    <% if @user != current_user %>
      <%= render 'follow_form'  %>
      <%= render 'block_form'  %>
      <%# link_to 'Back', users_path %>
    <% end %>

    <% if @user == current_user %>
      <div class="gapping">    </div>
    <% end %>

    <p class= "user_name-size">
      <strong><%= @user.user_name %></strong>
    </p>

    <p class="text-size">
      <strong><%= @user.name %></strong>
    </p>

    <p class="text-size">
      <!-- <strong>Bio: </strong> -->
      <%= @user.bio %>
    </p>

    <div class="first">
      <div class="second">
        <p class="text-size">
          <strong><%= @user.posts.count %></strong> <%= (@user.posts.count) == 1 ? 'Post' : 'Posts'%>
        </p>
      </div>
      <div class="second">
        <p class="text-size">
          <strong><%= @user.followers.count %></strong> <%= (@user.followers.count) == 1 ? 'Follower' : 'Followers'%>
        </p>
      </div>
      <div class="second">
        <p class="text-size">
          <strong><%= @user.following.count %></strong> <%= (@user.following.count) == 1 ? 'Following' : 'Followings'%>
        </p>
      </div>
    </div>
  </div>

  <div class="gapping">  </div>
  <div class="gapping">  </div>

  <div align = "left">
    <ul>
      <% @user.posts.each do |post| %>
        <div class="profile-post-gap">
          <li>
            <% post.images.each do |file| %>
              <% if file.representable? %>
                <%= image_tag file.representation(resize_to_limit: [400, 400]) %>
              <% end %>
            <% end %>
          </li>

          <div class="like-gap">
            <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
              <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete, class:"btn btn-danger" %>
            <% else %>
              <%= button_to 'Like', post_likes_path(post), method: :post, :class=> "btn btn-success" %>
            <% end %>
            <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
          </div>

          <p>
            <strong><%= post.caption %></strong>
          </p>

          <div class="">
            <% if @user == current_user %>
            <%= link_to "Edit", edit_post_path(post), :class=>"btn btn-outline-primary" %>
            <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }, :class=>"btn btn-outline-danger" %>
            <% end %>
          </div>

          <h7>Comments</h7>
          <%= render post.postcomments %>

        </div>
      <% end %>
    </ul>
  </div>
  <% else %>
    <h4>User dosen't exit </h4>
  <% end %>