config/routes.rb
Rails.application.routes.draw do

  # resources :msgs
  # resources :chats
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # resources :postcomments

  resources :posts do
    resources :postcomments
    resources :likes
  end

  # resources :posts do
  #   resources :likes
  # end

  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root to: "posts#index"

  resources :users, except: [:show] do
    member do
      get :following, :followers
      get :blocking, :blocked_by
    end
    collection do
      get :search
    end
  end

  get '/users/:user_name', to: 'users#show'

  resources :conversations do
    resources :messages
  end

  resources :chats do
    resources :msgs
  end

  get "/profile" => "users#profile"
  resources :relationships,       only: [:create, :destroy]
  resources :blocks,       only: [:create, :destroy]

  # API
  namespace :api do
    namespace :v1 do

     resources :posts
     resources :users
     resources :postcomments
     resources :likes
     resources :relationships do
       collection do
         post :follow
         post :unfollow
       end
     end
     resources :blocks do
       collection do
         post :block
         post :unblock
       end
     end

    end
  end
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, length: {maximum: 100}
end

app/controllers/api/v1/postcomments_controller.rb
class Api::V1::PostcommentsController < Api::V1::ApplicationController
  before_action :find_post
  before_action :set_article, only: [:show, :update, :destroy]
  # skip_before_action :verify_authenticity_token
  before_action :doorkeeper_authorize!

  def index
    @postcomments = @post.postcomments
    render json: @postcomments
  end

  def show
    render json: @postcomment
  end

  def create
    # p "------#{user_params}"
    @postcomment = Postcomment.new(postcomment_params)
    if @postcomment.save
      render json: @postcomment
    else
      render json: @postcomment.errors
    end
  end

  def update
    if @postcomment.update(postcomment_params)
      render json: @postcomment
    else
      render json: @postcomment.errors
    end
  end

  def destroy
    @postcomment.destroy
  end

private

  def postcomment_params
    params.require(:postcomment).permit(:content, :user_id, :post_id)
  end

  def set_article
   @postcomment = Postcomment.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < InheritedResources::Base

  def create
    # @postcomment.user_id = current_user.id
    @post = Post.find(params[:post_id])
    @postcomment = @post.postcomments.create(postcomment_params.merge(user_id: current_user.id))
    # redirect_to post_path(@post)
    redirect_to posts_path
  end


private

  def postcomment_params
    params.require(:postcomment).permit(:content, :user_id, :post_id)
  end

end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/views/postcomments/_form.html.erb
<%= form_with model: [ @post, @post.postcomments.build ] do |form| %>

  <p>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit "Comment" %>
  </p>

<% end %>

app/views/postcomments/_postcomment.html.erb
<p class= "content-size">
  <strong class="commenter-size"><%= postcomment&.user&.user_name %></strong> <%= postcomment.content %>
</p>

app/views/postcomments/edit.html.erb
<h1>Editing Postcomment</h1>

<%= render 'form', postcomment: @postcomment %>

<%= link_to 'Show', @postcomment %> |
<%= link_to 'Back', postcomments_path %>

app/views/postcomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postcomments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postcomments.each do |postcomment| %>
      <tr>
        <td><%= postcomment.content %></td>
        <td><%= postcomment.user_id %></td>
        <td><%= postcomment.post_id %></td>
        <td><%= link_to 'Show', postcomment %></td>
        <td><%= link_to 'Edit', edit_postcomment_path(postcomment) %></td>
        <td><%= link_to 'Destroy', postcomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postcomment', new_postcomment_path %>

app/views/postcomments/new.html.erb
<h1>New Postcomment</h1>

<%= render 'form', postcomment: @postcomment %>

<%= link_to 'Back', postcomments_path %>

app/views/postcomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @postcomment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @postcomment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @postcomment.post_id %>
</p>

<%= link_to 'Edit', edit_postcomment_path(@postcomment) %> |
<%= link_to 'Back', postcomments_path %>