config/routes.rb
Rails.application.routes.draw do

  # resources :msgs
  # resources :chats
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # resources :postcomments

  resources :posts do
    resources :postcomments
    resources :likes
  end

  # resources :posts do
  #   resources :likes
  # end

  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root to: "posts#index"

  resources :users, except: [:show] do
    member do
      get :following, :followers
      get :blocking, :blocked_by
    end
    collection do
      get :search
    end
  end

  get '/users/:user_name', to: 'users#show'

  resources :conversations do
    resources :messages
  end

  resources :chats do
    resources :msgs
  end

  get "/profile" => "users#profile"
  resources :relationships,       only: [:create, :destroy]
  resources :blocks,       only: [:create, :destroy]

  # API
  namespace :api do
    namespace :v1 do

     resources :posts
     resources :users
     resources :postcomments
     resources :likes
     resources :relationships do
       collection do
         post :follow
         post :unfollow
       end
     end
     resources :blocks do
       collection do
         post :block
         post :unblock
       end
     end

    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :blocked_by, class_name: "User"
  belongs_to :blocked, class_name: "User"
  validates :blocked_by_id, presence: true
  validates :blocked_id, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  has_many :msgs, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where("(chats.sender_id = ? AND   chats.recipient_id =?) OR (chats.sender_id = ? AND chats.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/msg.rb
class Msg < ApplicationRecord
  belongs_to :chat
  belongs_to :user

  validates_presence_of :body, :chat_id, :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :postcomments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :caption, presence:true, length: {maximum: 100}
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, length: {maximum: 100}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  acts_as_messageable

  # for change in url of user's profile
  # extend FriendlyId
  # friendly_id :user_name, use: :slugged

  # devise authentication
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #doorkeeper
  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end

  # Relationships
  has_many :posts, dependent: :destroy
  has_many :postcomments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image

  # validation to user model
  validates :name, presence: true
  validates :user_name, presence: true, uniqueness: true, length: {minimum: 5, maximum: 20}
  validates :email, presence: true, uniqueness: true
  validates :phone_no, presence: true, uniqueness: true, length: {maximum: 10}
  validates :bio, length: {maximum: 150}

  #doorkeeper
  has_many :access_grants,
           class_name: 'Doorkeeper::AccessGrant',
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
           class_name: 'Doorkeeper::AccessToken',
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  # Follow feature
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower


  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # Block feature
  has_many :active_blocks,  class_name:  "Block",
                                  foreign_key: "blocked_by_id",
                                  dependent:   :destroy
  has_many :blocking, through: :active_blocks,  source: :blocked

  has_many :passive_blocks, class_name:  "Block",
                                  foreign_key: "blocked_id",
                                  dependent:   :destroy
  has_many :blocked_by, through: :passive_blocks, source: :blocked_by

  # Blocks a user.
  def block(other_user)
    active_blocks.create(blocked_id: other_user.id)
  end

  # Unblocks a user.
  def unblock(other_user)
    active_blocks.find_by(blocked_id: other_user.id).destroy
  end

  # Returns true if the current user is blocking the other user.
  def blocking?(other_user)
    blocking.include?(other_user)
  end

  #csv download
  def self.to_csv
    attributes = %w{id email name user_name bio phone_no}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << user.attributes.values_at(*attributes)
      end
    end
  end

  # for Search
  def self.search(user_name)
    if user_name
      user_name.downcase!
      where('LOWER(user_name) LIKE ?', "%#{user_name}%")
    else
      all
    end
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    following = current_user.following.pluck(:id)
    blocked_by = current_user.blocked_by.pluck(:id)
    unblocked_following = following - blocked_by
    @users = User.where(id: unblocked_following)

    @chats = Chat.all
  end


  def create
    if Chat.between(params[:sender_id], params[:recipient_id]).present?
       @chat = Chat.between(params[:sender_id], params[:recipient_id]).first
    else
       @chat = Chat.create!(chat_params)
    end
    redirect_to chat_msgs_path(@chat)
  end

  private

    def chat_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController
  before_action do
    @chat = Chat.find(params[:chat_id])
  end

  def index
    @msgs = @chat.msgs
    @msg = @chat.msgs.new
  end

  def new
    @msg = @chat.msgs.new
  end

  def create
    @msg = @chat.msgs.new(msg_params)
    if @msg.save
      redirect_to chat_msgs_path(@chat)
    end
  end

  private

    def msg_params
      params.require(:msg).permit(:body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_home_nav.html.erb
<li class="nav-item active">
  <a class="nav-link" href="#">Home
    <span class="sr-only">(current)</span>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">About</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Services</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Contact</a>
</li>

app/views/layouts/_user_nav.html.erb
<li class="nav-item">
  <%= link_to "Home", posts_path, class: "nav-link" %>
</li>

<li class="nav-item">
  <%= link_to "Add Post", new_post_path, class: "nav-link" %>
</li>

<li class="nav-item">
<%= link_to "Find Friends", users_path, class: "nav-link" %>
</li>

<li class="nav-item">
<%= link_to "My Profile", profile_path, class: "nav-link" %>
</li>

<li class="nav-item">
<%# <%= link_to "Messaging", conversations_path, class: "nav-link" %>
</li>

<li class="nav-item">
<%= link_to "Chat", chats_path, class: "nav-link" %>
</li>

<li class="nav-item">
  <%= form_tag users_path, :method => 'get' do %>
     <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
</li>

<li class="nav-item">
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- saved from url=(0060)https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

      <title>Instagram</title>

    <link href="./Starter Template for Bootstrap_files/starter-template.css" rel="stylesheet">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg  static-top navbar-light bg-light"">
      <div class="container">
        <a class="navbar-brand hober" href="#">Instagram</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto ml-md-auto">
            <% if user_signed_in? %>
              <%= render "layouts/user_nav" %>
            <% else %>
              <%= render "layouts/home_nav" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>